version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "17:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: alpine
        versions:
          - 3.13.1
          - 3.13.2
          - 3.13.3
          - 3.13.4
      - dependency-name: golang
        versions:
          - 1.15.7.pre.alpine3.12
          - 1.15.8.pre.alpine3.12
          - 1.16.0.pre.alpine3.12
          - 1.16.1.pre.alpine3.12
          - 1.16.2.pre.alpine3.12
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "17:00"
    open-pull-requests-limit: 10
